version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  nuto-backend:
    image: jieuniaeyo/pinned-backend:latest
    container_name: pinned-backend
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nuto
