version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pinned
      MONGO_INITDB_ROOT_PASSWORD: pinned
    volumes:
      - mongo-data:/data/db

  pinned-backend:
    build: ./backend
    image: jieuniaeyo/pinned-backend:latest
    container_name: pinned-backend
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://pinned:pinned@mongo:27017/pinned?authSource=admin

volumes:
  mongo-data:
